#!/usr/bin/env python3
"""Generate C and HMI descriptors from the single settings metadata authority."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    schema = json.loads((ROOT / 'settings/registry.json').read_text())
    assert schema['schema'] == 2
    keys = schema['settings']
    assert len(keys) <= 64 and len({x['key'] for x in keys}) == len(keys)
    groups = list(dict.fromkeys(x['basename'] for x in keys))
    assert len(groups) <= 16
    enum = []
    rows = []
    for i, x in enumerate(keys):
        assert re.fullmatch(r'mibr-[a-zA-Z0-9.-]+', x['basename'])
        identifier = 'ALTSET_' + re.sub('[^A-Z0-9]', '_', x['key'].upper())
        enum.append(f'    {identifier} = {i},')
        fields = [x['key'], x['basename'], x.get('field', ''), x['type'],
                  '|'.join(x.get('allowed', [])), x['default']['omonob790'],
                  x['default']['mibr_dual_view'], x['default']['mibr_legacy'],
                  x['apply'], x['hmi']]
        assert all(isinstance(v, str) for v in fields)
        assert all(len(v) < 192 for v in fields[5:8])
        nums = [x.get('min', 0), x.get('max', 0), groups.index(x['basename']),
                int(x.get('read_only', False))]
        rows.append('    {' + ', '.join(json.dumps(v) for v in fields) + ', ' +
                    ', '.join(str(v) for v in nums) + '},')
    header = ('/* Generated by tools/generate_alt111_settings.py. Do not edit. */\n'
              '#ifndef MIBR_ALT111_REGISTRY_GENERATED_H\n'
              '#define MIBR_ALT111_REGISTRY_GENERATED_H\n'
              'enum alt111_setting_id {\n' + '\n'.join(enum) +
              f'\n    ALTSET_COUNT = {len(keys)}\n}};\n'
              f'#define ALTSET_GROUP_COUNT {len(groups)}u\n#endif\n')
    table = ('/* Generated private descriptors. Do not edit. */\n'
             'static const struct alt111_setting_descriptor registry[] = {\n' +
             '\n'.join(rows) + '\n};\n')
    hmi = {'schema': schema['schema'], 'authority': 'settings/registry.json',
           'layer_order': schema['layer_order'], 'settings': keys}
    return {
        ROOT / 'src/native/alt111-settings/include/registry_generated.h': header,
        ROOT / 'src/native/alt111-settings/include/registry_table_generated.h': table,
        ROOT / 'settings/hmi-bindings.generated.json': json.dumps(hmi, indent=2) + '\n',
        ROOT / 'settings/runtime-basenames.generated.sh':
            "# Generated from settings/registry.json. Do not edit.\n" +
            "ALT111_CONFIG_BASENAMES='" + ' '.join(groups) + "'\n"
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, data in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != data:
                raise SystemExit(f'stale generated metadata: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data, newline='\n')
    print('ALT111_SETTINGS_SCHEMA=PASS')

if __name__ == '__main__':
    main()
